### ISSUE TITLE
How to run the project?

### ISSUE THREAD

**Issue by Ixiaohuihuihui** [stv0g/pastie#1]
Dear author:
  I have a problem, how to run the project? The platform is on visual studio?

**Comment by stv0g** [comment]
Hi,
The code has been written with QtCreator and is compiled by the usual qmake and make flow used by Qt projects.

Let me know if I can assist you.
I hope that my my code is useful for you! 😀

**Comment by dlhhuihuihui** [comment]
Thank u very much! Thanks for  your  answer! That's useful for me!
